#!/bin/bash

export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=5
BACKTITLE="Seleção de resolução"
TITLE="vncserver-start"
MENU="Choose any of the following options:"
export PORT=1


OPTIONS=(1 "Start vncserver in Ultrawide HD resolution"
         2 "Start vncserver in Quad-HD resolution"
         3 "Start vncserver in Full-HD resolution"
         4 "Start vncserver in HD resolution"
         5 "Start vncserver with custom resolution and port")



CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
1)
echo "You chose UWHD resolution"
GEO="-geometry 2560x1080" vnc
;;
2)
echo "You chose QHD resolution"
GEO="-geometry 2560x1440" vnc
;;
3)
echo "You chose Full HD resolution"
GEO="-geometry 1920x1080" vnc
;;
4)
echo "You chose HD resolution"
GEO="-geometry 1280x720" vnc
;;
5)
echo "You chose to set the resolution and port manually"
echo "Enter your custom resolution in the format WIDTHxHEIGHT.  Example: 1920x1200"
read custom
echo "Enter the port number.  Example: 2"
read port
GEO="-geometry $custom" PORT=$port vnc
;;
esac

bash --login