#!/bin/bash
extralink="https://raw.githubusercontent.com/allytiago/Ubuntu-no-Android/beta/config"

echo -e  "\033[0;34m =========================================================== \033[0m"
echo -e  "\033[0;34m =========================================================== \033[0m"
echo -e  "\033[0;34m =========================================================== \033[0m"


echo "




"
echo -e  "\033[0;31m =========================================================== \033[0m"
rm -rf /usr/local/bin/startvncserver
wget --tries=20 "$extralink/startconfig-2" -O /usr/local/bin/startvncserver > /dev/null
chmod +x /usr/local/bin/startvncserver
echo "




"
echo -e  "\033[0;32m =========================================================== \033[0m"
bash ~/language-base.sh



