#!/bin/bash

rm -rf /usr/local/bin/startvncserver
bash ~/language-base.sh

if [ ! -f language-base.sh ]; then
    wget --tries=20 "$extralink/tigervnc/startvncserver" -P usr/local/bin > /dev/null
    chmod +x ubuntu22-fs/usr/local/bin/startvncserver
fi

bash ~/ui-config.sh
bash ~/language-base.sh