#!/bin/bash
extralink="https://raw.githubusercontent.com/allytiago/Ubuntu-no-Android/beta/config"

echo -e  "\033[0;34m =========================================================== \033[0m"
echo -e  "\033[0;34m =========================================================== \033[0m"
echo -e  "\033[0;34m =========================================================== \033[0m"


echo "




"
echo -e  "\033[0;31m =========================================================== \033[0m"
rm -rf /usr/local/bin/startvncserver
echo "




"
echo -e  "\033[0;32m =========================================================== \033[0m"
bash ~/language-base.sh

if [ ! -f language-base.sh ]; then
    echo -e  "\033[0;35m =========================================================== \033[0m"
    wget --tries=20 "$extralink/tigervnc/startvncserver" -P /usr/local/bin > /dev/null
    chmod +x /usr/local/bin/startvncserver
fi

echo -e  "\033[0;34m =========================================================== \033[0m"

sudo apt-get install dialog -y
sudo apt-get install keyboard-configuration -y
sudo apt-get install tzdata -y #dpkg-reconfigure tzdata

echo "



"
echo "Execução sussedida"

#bash ~/ui-config.sh
