#!/bin/bash
LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncserver -localhost no -depth 24 -name remote-desktop $GEO :$PORT
echo "Servidor VNC foi iniciado. A senha padrão é a senha da conta para $USER"
