#!/bin/bash

export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=5
BACKTITLE="Seleção de resolução"
TITLE="vncserver-start"
MENU="Escolha alguma das seguintes opções:"
export PORT=1

OPTIONS=(1 "Iniciar o vncserver com detecção automática de resolução"
         2 "Iniciar o vncserver na resolução Ultrawide HD"
         3 "Iniciar o vncserver na resolução Quad-HD"
         4 "Iniciar o vncserver na resolução Full-HD"
         5 "Iniciar o vncserver na resolução HD"
         6 "Iniciar o vncserver com resolução e porta customizada"
         7 "Iniciar o vncserver com resolução, porta e escala customizada")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "Você escolheu a detecção automática de resolução"
            GEO="" vnc && xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1
            ;;
        2)
            echo "Você escolheu a resoluçãoUWHD resolution"
            GEO="-geometry 2560x1080" vnc && xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1
            ;;
        3)
            echo "Você escolheu a resolução QHD resolution"
            GEO="-geometry 2560x1440" vnc && xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1
            ;;
        4)
            echo "Você escolheu a resolução Full HD resolution"
            GEO="-geometry 1920x1080" vnc && xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1
            ;;
        5)
            echo "Você escolheu a resolução HD-ready resolution"
            GEO="-geometry 1280x720" vnc && xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1
            ;;
        6)
            echo "Você escolheu definir a resolução e porta manualmente"
            echo "Insira a resolução personalizada no formato WIDTHxHEIGHT (LARGURA x ALTURA). Exemplo: 1920x1200"
            read custom
            echo "Insira o número da porta. Exemplo: 2"
            read port
            GEO="-geometry $custom" PORT=$port vnc && xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1
            ;;
         7)
            echo "Você escolheu definir a resolução e porta manualmente"
            echo "Insira a resolução personalizada no formato WIDTHxHEIGHT (LARGURA x ALTURA). Exemplo: 1920x1200"
            read custom
            echo "Insira o número da porta. Exemplo: 2"
            read port
            echo "Insira o número da escala. Exemplo: 2"
            read scaling
            GEO="-geometry $custom" PORT=$port vnc && xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s $scaling
            ;;
esac
